### ISSUE TITLE
line 90 in 'functions.r'?

### ISSUE THREAD

**Issue by yingji15** [XingjieShi/TisCoMM#1]
Hi there, thanks for making this code public! It's very well-written, very helpful!

I am wondering in line 90 of 'functions.r', is that possible that you mean 
`pc_top <- yhat2_pca$x[,ind_top]`

Because the `ind_top` was extracted and not used, and it seems here we are trying to only use those PCs of high importance for testing. But I could be wrong, so it'll be great to hear from you!

Ying

**Comment by XingjieShi** [comment]
Hi Ying,

Thanks for pointing that out. You are correct, I have already updated the
code. In our paper, this function is only used for simulations with ten
tissues. So there would be no different whether you use this "ind_top" or
not. But in the case of large amounts of tissues, we do need to use top
PCs, as the multixcan authors suggested.

Feel free to let me know if you have any further questions.


Best,
Xingjie

**Comment by yingji15** [comment]
Thanks for the explanation! That makes sense!

Best,
Ying
